on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.1'

      - name: Set up Keys
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.HOSTINGER_GITHUB_SSH_KEY }}
          ssh-host: ${{ secrets.HOSTINGER_REMOTE_SERVER_IP }}

      - name: Deploy
        env:
          HOSTINGER_REMOTE_SERVER_IP: ${{ secrets.HOSTINGER_REMOTE_SERVER_IP }}
        run: make deploy
